version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=money
      - POSTGRES_USER=santi
      - POSTGRES_PASSWORD=money123
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=santi@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - 5050:80
